project:
  type: website
  output-dir: _site

website:
  title: "tidy tuesday"
  description: "A collection of data visualizations for Tidy Tuesday challenges"
  search: false
   
  navbar:
    title: "tidy tuesday"
    left:
#      - href: index.qmd
#        text: Home
      - href: about.qmd
        text: About
      - text: "↩ Return to Website"
        href: https://aaronwriight.github.io/
    
    tools:
      - icon: github
        href: https://github.com/aaronwriight/tidytuesday
      - icon: twitter
        href: https://bsky.app/profile/aaronwriight.bsky.social
      - icon: linkedin
        href: https://www.linkedin.com/in/aaron-wriight/
      - icon: envelope
        href: mailto:aawva@mit.edu
        

format:
  html:
    theme: 
      - flatly
      - styles.scss
    toc-location: right
    toc: false
    code-fold: true
    highlight-style: github
    include-in-header: 
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 200px

execute:
  freeze: auto
  warning: false
  message: false
